"""init

Revision ID: 243ff3aab6e1
Revises: 
Create Date: 2026-01-15 19:57:55.534532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243ff3aab6e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'APPROVER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_user_email'), 'identity_user', ['email'], unique=True)
    op.create_index(op.f('ix_identity_user_role'), 'identity_user', ['role'], unique=False)
    op.create_table('claims_claim',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('home_currency', sa.String(length=3), nullable=False),
    sa.Column('travel_start_date', sa.Date(), nullable=True),
    sa.Column('travel_end_date', sa.Date(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'NEEDS_EMPLOYEE_REVIEW', 'SUBMITTED', 'NEEDS_APPROVER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'READY_FOR_PAYMENT', 'PAID', 'REJECTED', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['identity_user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['identity_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_status'), 'claims_claim', ['status'], unique=False)
    op.create_table('audit_event',
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity_user.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_actor_user_id'), 'audit_event', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_event_claim_id'), 'audit_event', ['claim_id'], unique=False)
    op.create_index(op.f('ix_audit_event_event_type'), 'audit_event', ['event_type'], unique=False)
    op.create_table('documents_source_file',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='sourcefilestatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['identity_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_source_file_claim_id'), 'documents_source_file', ['claim_id'], unique=False)
    op.create_index(op.f('ix_documents_source_file_sha256'), 'documents_source_file', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_source_file_status'), 'documents_source_file', ['status'], unique=False)
    op.create_table('expenses_expense_item',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('vendor_reference', sa.String(length=200), nullable=True),
    sa.Column('receipt_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_original_currency', sa.String(length=3), nullable=False),
    sa.Column('amount_home_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_home_currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_home', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'dedupe_key', name='uq_expense_claim_dedupe'),
    sa.UniqueConstraint('vendor', 'vendor_reference', name='uq_expense_vendor_reference')
    )
    op.create_index(op.f('ix_expenses_expense_item_claim_id'), 'expenses_expense_item', ['claim_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_item_receipt_type'), 'expenses_expense_item', ['receipt_type'], unique=False)
    op.create_index(op.f('ix_expenses_expense_item_vendor'), 'expenses_expense_item', ['vendor'], unique=False)
    op.create_table('exports_export_run',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='exportstatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary_xlsx_key', sa.String(length=1024), nullable=True),
    sa.Column('supporting_zip_key', sa.String(length=1024), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['identity_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_export_run_claim_id'), 'exports_export_run', ['claim_id'], unique=False)
    op.create_index(op.f('ix_exports_export_run_status'), 'exports_export_run', ['status'], unique=False)
    op.create_table('fx_rate',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'from_currency', 'to_currency', name='uq_fx_claim_pair')
    )
    op.create_index(op.f('ix_fx_rate_claim_id'), 'fx_rate', ['claim_id'], unique=False)
    op.create_table('workflow_approval',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('approver_user_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'CHANGES_REQUESTED', 'REJECTED', name='approvaldecision', native_enum=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['identity_user.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approval_claim_id'), 'workflow_approval', ['claim_id'], unique=False)
    op.create_index(op.f('ix_workflow_approval_decision'), 'workflow_approval', ['decision'], unique=False)
    op.create_table('documents_evidence_document',
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('receipt_type', sa.String(length=50), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['documents_source_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_evidence_document_receipt_type'), 'documents_evidence_document', ['receipt_type'], unique=False)
    op.create_index(op.f('ix_documents_evidence_document_source_file_id'), 'documents_evidence_document', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_documents_evidence_document_text_hash'), 'documents_evidence_document', ['text_hash'], unique=False)
    op.create_index(op.f('ix_documents_evidence_document_vendor'), 'documents_evidence_document', ['vendor'], unique=False)
    op.create_table('policy_violation',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('expense_item_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Enum('PASS', 'WARN', 'FAIL', 'NEEDS_INFO', name='policyseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='violationstatus', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.ForeignKeyConstraint(['expense_item_id'], ['expenses_expense_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_policy_violation_dedupe')
    )
    op.create_index(op.f('ix_policy_violation_claim_id'), 'policy_violation', ['claim_id'], unique=False)
    op.create_index(op.f('ix_policy_violation_severity'), 'policy_violation', ['severity'], unique=False)
    op.create_index(op.f('ix_policy_violation_status'), 'policy_violation', ['status'], unique=False)
    op.create_table('workflow_task',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('expense_item_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['identity_user.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claim.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['identity_user.id'], ),
    sa.ForeignKeyConstraint(['expense_item_id'], ['expenses_expense_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_task_claim_id'), 'workflow_task', ['claim_id'], unique=False)
    op.create_index(op.f('ix_workflow_task_status'), 'workflow_task', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_task_type'), 'workflow_task', ['type'], unique=False)
    op.create_table('expenses_expense_item_evidence',
    sa.Column('expense_item_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents_evidence_document.id'], ),
    sa.ForeignKeyConstraint(['expense_item_id'], ['expenses_expense_item.id'], ),
    sa.PrimaryKeyConstraint('expense_item_id', 'evidence_document_id'),
    sa.UniqueConstraint('expense_item_id', 'evidence_document_id', name='uq_item_evidence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses_expense_item_evidence')
    op.drop_index(op.f('ix_workflow_task_type'), table_name='workflow_task')
    op.drop_index(op.f('ix_workflow_task_status'), table_name='workflow_task')
    op.drop_index(op.f('ix_workflow_task_claim_id'), table_name='workflow_task')
    op.drop_table('workflow_task')
    op.drop_index(op.f('ix_policy_violation_status'), table_name='policy_violation')
    op.drop_index(op.f('ix_policy_violation_severity'), table_name='policy_violation')
    op.drop_index(op.f('ix_policy_violation_claim_id'), table_name='policy_violation')
    op.drop_table('policy_violation')
    op.drop_index(op.f('ix_documents_evidence_document_vendor'), table_name='documents_evidence_document')
    op.drop_index(op.f('ix_documents_evidence_document_text_hash'), table_name='documents_evidence_document')
    op.drop_index(op.f('ix_documents_evidence_document_source_file_id'), table_name='documents_evidence_document')
    op.drop_index(op.f('ix_documents_evidence_document_receipt_type'), table_name='documents_evidence_document')
    op.drop_table('documents_evidence_document')
    op.drop_index(op.f('ix_workflow_approval_decision'), table_name='workflow_approval')
    op.drop_index(op.f('ix_workflow_approval_claim_id'), table_name='workflow_approval')
    op.drop_table('workflow_approval')
    op.drop_index(op.f('ix_fx_rate_claim_id'), table_name='fx_rate')
    op.drop_table('fx_rate')
    op.drop_index(op.f('ix_exports_export_run_status'), table_name='exports_export_run')
    op.drop_index(op.f('ix_exports_export_run_claim_id'), table_name='exports_export_run')
    op.drop_table('exports_export_run')
    op.drop_index(op.f('ix_expenses_expense_item_vendor'), table_name='expenses_expense_item')
    op.drop_index(op.f('ix_expenses_expense_item_receipt_type'), table_name='expenses_expense_item')
    op.drop_index(op.f('ix_expenses_expense_item_claim_id'), table_name='expenses_expense_item')
    op.drop_table('expenses_expense_item')
    op.drop_index(op.f('ix_documents_source_file_status'), table_name='documents_source_file')
    op.drop_index(op.f('ix_documents_source_file_sha256'), table_name='documents_source_file')
    op.drop_index(op.f('ix_documents_source_file_claim_id'), table_name='documents_source_file')
    op.drop_table('documents_source_file')
    op.drop_index(op.f('ix_audit_event_event_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_claim_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_user_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_claims_claim_status'), table_name='claims_claim')
    op.drop_table('claims_claim')
    op.drop_index(op.f('ix_identity_user_role'), table_name='identity_user')
    op.drop_index(op.f('ix_identity_user_email'), table_name='identity_user')
    op.drop_table('identity_user')
    # ### end Alembic commands ###
